### ISSUE TITLE
[4.0] "Reserved indicator ` cannot start a plain scalar" on Travis CI builds for a module

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6574]
A recent Travis build using the latest master branch of the framework failed to parse configuration:

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'The reserved indicator "`" cannot start a plain scalar; you need to quote the scalar at line 34 (near "2: `TEMP_FOLDER`").' in phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php:321
Stack trace:
#0 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php(107): Symfony\Component\Yaml\Inline::parseScalar('`TEMP_FOLDER`', 0, NULL, Array, 13, true, Array)
#1 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(598): Symfony\Component\Yaml\Inline::parse('`TEMP_FOLDER`', 0, Array)
#2 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(261): Symfony\Component\Yaml\Parser->parseValue('`TEMP_FOLDER`', 0, 'mapping')
#3 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(354): Symfony\Component\Yaml\Parser->parse('0: 'en'\n1: null...', 0 in phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php on line 321
```

The line was probably added in #6558.

I can't reproduce this locally, but it happens consistently on Travis.

**Comment by robbieaverill** [comment]
It's worth noting that this Travis build is using PHPUnit 5.7. I probably tested it against 4.8 locally, hence not being able to reproduce it locally.

PHPUnit 5.7 has a loose constraint for `symfony/yaml`, but could (and probably does) pull `~3.0`. The framework uses `~2.7`.

@tractorcow this is probably worth closing for now but keeping in mind for the future when you upgrade that component.

**Comment by tractorcow** [comment]
Yep, we can fix by just quoting that identifier. thanks for the heads up.

**Comment by tractorcow** [comment]
Time to add a 5.7 php build.
