### ISSUE TITLE
Circular dependency found

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#8507]
```
Fatal error: Uncaught MJS\TopSort\CircularDependencyException:
Circular dependency found: debugbarext->debugbarext in /home/test/ss/vendor/marcj/topsort/src/CircularDependencyException.php:34

Stack trace:
 #0 /home/test/ss/vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create(Array) 
 #1 /home/test/ss/vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array) 
 #2 /home/test/ss/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array) 
 #3 /home/test/ss/vendor/marcj/topsort/src/Implementations/ArraySort.php(115): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array) 
 #4 /home/test/ss/vendor/marcj/topsort/src/Implementations/ArraySort.php(98): MJS\TopSort\Implementations\ArraySort->doSort()
 #5 /home/test in /home/test/ss/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```

composer info:
```
a2nt/silverstripe-font-awesome-field              dev-master 4635537 A simple form field for selecting font...
axllent/silverstripe-bootstrap-forms              2.0.3              An extension to add CSS classes to Sil...
axllent/silverstripe-version-truncator            2.0.3              Automatically delete old SiteTree page...
betterbrief/silverstripe-googlemapfield           v2.2.1             Save locations using latitude/longitud...
colymba/gridfield-bulk-editing-tools              v2.1.10            SilverStripe 3 GridField component to ...
composer/ca-bundle                                1.1.3              Lets you find a path to the system CA ...
composer/installers                               v1.6.0             A multi-framework Composer library ins...
dnadesign/silverstripe-elemental                  3.0.0              Elemental pagetype and collection of E...
dnadesign/silverstripe-elemental-list             1.1.0              Adds a new element for nested elements
dnadesign/silverstripe-elemental-userforms        2.0.0              Adds a new element for usersforms
dnadesign/silverstripe-elemental-virtual          1.1.0              Adds ability for Elemental to share co...
drmartingonzo/ss-tinymce-charcount                1.0.0              Plugin for tinyMCE in siverstripe to c...
dynamic/flexslider                                3.0.3              Display a FlexSlider on pages of your ...
dynamic/silverstripe-elemental-accordion          1.0.0              Display content in collapsable panels
dynamic/silverstripe-elemental-baseobject         1.0.0              A simple base DataObject to use with E...
dynamic/silverstripe-elemental-blocks             2.0.0              A recipe to require additonal elements...
dynamic/silverstripe-elemental-blog               1.0.1              A blog element for the SilverStripe El...
dynamic/silverstripe-elemental-countdown          1.0.0-beta1        Additional count down element for the ...
dynamic/silverstripe-elemental-customer-service   1.0.0              Additional customer service element fo...
dynamic/silverstripe-elemental-embedded-code      1.0.1              A block to embed code like iFrames or ...
dynamic/silverstripe-elemental-features           1.0.0              A block that displays featured content...
dynamic/silverstripe-elemental-flexslider         1.0.1              Flexslider slideshow content block for...
dynamic/silverstripe-elemental-gallery            1.0.1              A block to display a collection of images
dynamic/silverstripe-elemental-image              1.0.1              A block to add a single image to your ...
dynamic/silverstripe-elemental-oembed             1.0.0              A block to embed media from other webs...
dynamic/silverstripe-elemental-promos             1.0.1              A block to display a group of promo ob...
dynamic/silverstripe-elemental-section-navigation 1.0.2              A block to display a list of links to ...
dynamic/silverstripe-elemental-sponsors           1.0.0              A sponsors element for the SilverStrip...
dynamic/silverstripe-elemental-testimonials       1.0.1              Testimonials element for the SilverStr...
dynamic/silverstripe-geocoder                     dev-master 1f2dc56 SilverStripe wrapper for Geocoder
egeloen/http-adapter                              0.8.0              Issue HTTP request for PHP 5.3+.
embed/embed                                       v3.3.6             PHP library to retrieve page info usin...
firesphere/googlemapsfield                        dev-master ecf39a4 Google places api field for SilverStripe
gorriecoe/silverstripe-dataobjecthistory          1.2.2              Adds a history tab to dataobjects
guzzlehttp/psr7                                   1.4.2              PSR-7 message implementation that also...
igorw/get-in                                      v1.0.3             Functions for for hash map (assoc arra...
innoweb/silverstripe-sitemap                      2.1.1              Adds a page type that automatically bu...
intervention/image                                2.4.2              Image handling and manipulation librar...
jonom/silverstripe-betternavigator                4.1.1              Front-end utility menu for SilverStrip...
league/csv                                        8.2.3              Csv data manipulation made easy in PHP
league/flysystem                                  1.0.48             Filesystem abstraction: Many filesyste...
m1/env                                            2.1.2              Env is a lightweight library bringing ...
marcj/topsort                                     1.1.0              High-Performance TopSort/Dependency re...
monolog/monolog                                   1.23.0             Sends your logs to files, sockets, inb...
nikic/php-parser                                  v3.1.5             A PHP parser written in PHP
paragonie/random_compat                           v2.0.17            PHP 5.x polyfill for random_bytes() an...
psr/cache                                         1.0.1              Common interface for caching libraries
psr/container                                     1.0.0              Common Container Interface (PHP FIG PS...
psr/http-message                                  1.0.1              Common interface for HTTP messages
psr/log                                           1.0.2              Common interface for logging libraries
psr/simple-cache                                  1.0.1              Common interfaces for simple caching
sheadawson/silverstripe-dependentdropdownfield    2.0.0              A silverstripe dropdown field that has...
sheadawson/silverstripe-linkable                  2.0.0              A couple of handy form fields and obje...
silverstripe/admin                                1.2.1              SilverStripe admin interface
silverstripe/asset-admin                          1.2.1              Asset management for the SilverStripe CMS
silverstripe/assets                               1.2.1              SilverStripe Assets component
silverstripe/blog                                 3.2.1              A fresh take on blogging in Silverstri...
silverstripe/campaign-admin                       1.2.1              SilverStripe campaign admin interface
silverstripe/cms                                  4.2.1              The SilverStripe Content Management Sy...
silverstripe/config                               1.0.6              SilverStripe configuration based on YA...
silverstripe/errorpage                            1.2.1              ErrorPage component for SilverStripe CMS
silverstripe/externallinks                        2.0.2              Adds tracking of broken external links...
silverstripe/framework                            4.2.1              The SilverStripe framework
silverstripe/graphql                              2.0.1              GraphQL server for SilverStripe models...
silverstripe/lumberjack                           2.0.1              A module to make managing pages in a G...
silverstripe/recaptcha                            dev-master 6c839da Provides a form field which allows for...
silverstripe/recipe-cms                           4.2.1              SilverStripe recipe for fully featured...
silverstripe/recipe-core                          4.2.1              SilverStripe framework-only core recipe
silverstripe/recipe-plugin                        1.3.0              Helper plugin to install SilverStripe ...
silverstripe/redirectedurls                       dev-master 042ece4 Provides a system for users to configu...
silverstripe/reports                              4.2.1              Reports module for SilverStripe CMS
silverstripe/segment-field                        2.2.1              A reusable approach to segment-generat...
silverstripe/siteconfig                           4.2.1              Site wide settings administration.
silverstripe/spamprotection                       3.0.0              Spam protection module for SilverStripe.
silverstripe/tagfield                             2.1.0              Tag field for Silverstripe
silverstripe/userforms                            5.2.2              UserForms enables CMS users to create ...
silverstripe/vendor-plugin                        1.3.3              Allows vendor modules to expose direct...
silverstripe/versioned                            1.2.1              SilverStripe Versioned component
silverstripe/versioned-admin                      1.0.0              SilverStripe versioned admin interface
stevie-mayhew/silverstripe-svg                    2.1.0              Basic SVG support for SilverStripe
swiftmailer/swiftmailer                           v5.4.12            Swiftmailer, free feature-rich PHP mailer
symbiote/silverstripe-gridfieldextensions         3.2.0              A collection of useful grid field comp...
symfony/cache                                     v3.4.17            Symfony Cache component with PSR-6, PS...
symfony/config                                    v3.4.17            Symfony Config Component
symfony/filesystem                                v4.1.6             Symfony Filesystem Component
symfony/finder                                    v3.4.17            Symfony Finder Component
symfony/polyfill-apcu                             v1.9.0             Symfony polyfill backporting apcu_* fu...
symfony/polyfill-ctype                            v1.9.0             Symfony polyfill for ctype functions
symfony/polyfill-mbstring                         v1.9.0             Symfony polyfill for the Mbstring exte...
symfony/translation                               v2.8.46            Symfony Translation Component
symfony/yaml                                      v3.4.17            Symfony Yaml Component
unclecheese/display-logic                         2.0.1              Allows assignment of conditions for di...
undefinedoffset/silverstripe-nocaptcha            2.0.0              A spam protector and form field using ...
undefinedoffset/sortablegridfield                 2.0.6              Adds drag and drop functionality to Si...
webonyx/graphql-php                               v0.8.0             A PHP port of GraphQL reference implem...
willdurand/geocoder                               v3.3.0             The almost missing Geocoder PHP 5.4 li...
wilr/silverstripe-googlesitemaps                  2.1.2              SilverStripe support for the Google Si...
zendframework/zend-diactoros                      1.8.6              PSR HTTP Message implementations
```

**Comment by dhensby** [comment]
I don't expect that this is a framework bug; it looks like it's something to do with [debugbar](https://github.com/lekoala/silverstripe-debugbar)... but I'm not sure, you'll need to investigate the cause of the circular dep but it's definitely not from a vanilla framework install

**Comment by lerni** [comment]
Ran into the same error. An "After: - 'cms/*'" roule in a module _config was the trigger.
